### ISSUE TITLE
Uncaught TypeError: Error.captureStackTrace is not a function

### ISSUE THREAD

**Issue by Ragnar-Oock** [qphi/publisher-subscriber#7]
`Error.captureStackTrace` is called in the constructor of `SubscriptionNotFoundException` but it is only available in Node and thus throws `Uncaught TypeError: Error.captureStackTrace is not a function` when a `SubscriptionNotFoundException` happens.

tested in Firefox 96.0.3 and Chrome 97.0.4692.99

**Comment by qphilippot** [comment]
solved in #8
